services:
  registry:
    restart: always
    image: registry:3
    ports:
      - 5000:5000
    environment:
      #REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      #REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      #REGISTRY_AUTH: htpasswd
      #REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      #REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - /vault/homelab/volumes/registry/data:/var/lib/registry
      - /vault/homelab/volumes/registry/certs:/certs
      - /vault/homelab/volumes/registry/auth:/auth

  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    # Choose the appropriate tag based on your need:
    # - "latest" for the latest stable version (which could become 2.x.y
    #   in the future and break things)
    # - "1" for the latest stable version whose major version is 1
    # - "1.x.y" to pin the specific version 1.x.y
    network_mode: host
    # This bypasses network isolation and makes IPv6 easier (optional; see below)
    restart: always
    # Restart the updater after reboot
    user: "1000:1000"
    # Run the updater with specific user and group IDs (in that order).
    # You can change the two numbers based on your need.
    read_only: true
    # Make the container filesystem read-only (optional but recommended)
    cap_drop: [all]
    # Drop all Linux capabilities (optional but recommended)
    security_opt: [no-new-privileges:true]
    # Another protection to restrict superuser privileges (optional but recommended)
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - DOMAINS=home.${HOME_DOMAIN}
      - PROXIED=true

  public-tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    network_mode: host
    command:
      - "tunnel"
      - "--no-autoupdate"
      - "run"
    environment:
      - TUNNEL_TOKEN=${HOME_TUNNEL_TOKEN}

  docker-public-tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    command:
      - "tunnel"
      - "--no-autoupdate"
      - "run"
    environment:
      - TUNNEL_TOKEN=${DOCKER_TUNNEL_TOKEN}

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /vault/homelab/volumes/deluge/config:/config
      - /vault/media:/media
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 #optional
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=999
      - TZ=Etc/UTC
      #- JELLYFIN_PublishedServerUrl=http://192.168.0.5 #optional
    volumes:
      - /vault/homelab/volumes/jellyfin/config:/config
      - /vault/media/:/vault/media/
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped


  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - TZ=${TZ}
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - /vault/homelab/volumes/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro


#  discord-bot:
#    image: localhost:5000/discord-bot:v1.0.1
#    container_name: discord-bot
#    pull_policy: always
#    restart: unless-stopped
#    environment:
#      - DISCORD_TOKEN=${DISCORD_TOKEN}
#      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}

